### ISSUE TITLE
ECHO is a reserved word

### ISSUE THREAD

**Issue by jimmcq** [NicklasWallgren/pogoprotos-php#1]
PHP Parse error:  syntax error, unexpected 'ECHO' (T_ECHO), expecting identifier (T_STRING)
in src/POGOProtos/Networking/Requests/RequestType.php on line 76

**Comment by NicklasWallgren** [comment]
Resolved in latest commit.

**Comment by jimmcq** [comment]
Looks good now!  Thanks!
👍
