### ISSUE TITLE
UNSET is a reserved word

### ISSUE THREAD

**Issue by jimmcq** [NicklasWallgren/pogoprotos-php#2]
PHP Parse error:  syntax error, unexpected 'UNSET' (T_UNSET), expecting identifier (T_STRING)
in src/POGOProtos/Networking/Responses/ReleasePokemonResponse.php on line 15

**Comment by NicklasWallgren** [comment]
Resolved in latest commit.

**Comment by jimmcq** [comment]
Looks good now!  Thanks!
👍
