### ISSUE TITLE
const ECHO = 666; in RequestType.php causes syntax error

### ISSUE THREAD

**Issue by SchwarzwaldFalke** [NicklasWallgren/pogoprotos-php#6]
Commit 4285377a80b4a20c698489a9614f3d6cc4746d82 replaces
`
const PING = 666;
`
with
`
const ECHO = 666;
`
in RequestType.php

This causes problems in PHP 5.6 since ECHO is a reserved key word (NicklasWallgren/PokemonGoAPI-PHP#46)

**Comment by baskettcase** [comment]
Yep Im having this problem

**Comment by NicklasWallgren** [comment]
Sorted, my bad.
