### ISSUE TITLE
New PokemonData item, number 33.

### ISSUE THREAD

**Issue by rjahpa** [NicklasWallgren/pogoprotos-php#7]
Hello, 

I realized that a new item in the file **PokemonData.php** that was causing an error has been added, I added the following lines and work, do not know what these values, but I think I came to update 0.39.

```
      case 32: // optional int32 buddy_candy_awarded = 32
        if($wire !== 0) {
          throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
        }
        $tmp = Protobuf::read_signed_varint($fp, $limit);
        if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
        if ($tmp < Protobuf::MIN_INT32 || $tmp > Protobuf::MAX_INT32) throw new \Exception('int32 out of range');$this->buddyCandyAwarded = $tmp;

        break;
      case 33: // optional float unknow item = 33
        $tmp = Protobuf::read_float($fp, $limit);

        break;
      default:
        $limit -= Protobuf::skip_field($fp, $wire);
```

**Comment by DrDelay** [comment]
Can confirm that this "fixes" the buddy-candy-related error discussed in https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/142. I also tested an account with no such buddy pokemon, this also still worked.

**Comment by NicklasWallgren** [comment]
Perfect, the master branch has been updated.

https://github.com/NicklasWallgren/pogoprotos-php/commit/1c3609c4c7ab4da5dc58f56427f691b8226f2384
